"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Printer, RefreshCw } from "lucide-react";

export default function ReceiptPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [payment, setPayment] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/v1/payments/${id}`)
      .then((r) => r.json())
      .then((json) => { if (json.success) setPayment(json.data.payment); })
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <div className="py-20 flex items-center justify-center text-slate-400">
        <RefreshCw className="w-5 h-5 animate-spin text-emerald-500 mr-2" /> Loading receipt…
      </div>
    );
  }
  if (!payment) {
    return (
      <div className="text-center py-20 text-slate-400">
        <p>Receipt not found.</p>
        <Link href="/payments" className="text-emerald-400 text-xs hover:underline mt-2 inline-block">Back to payments</Link>
      </div>
    );
  }

  const property = payment.property;
  const brand = property?.brand_color || "#059669";
  const symbol = property?.currency_symbol || "₹";
  const fmt = (n: number) => `${symbol}${(n || 0).toLocaleString()}`;
  const reversed = payment.status === "reversed";

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      <style>{`@media print {
        body * { visibility: hidden !important; }
        #receipt-print, #receipt-print * { visibility: visible !important; }
        #receipt-print { position: absolute; left: 0; top: 0; width: 100%; box-shadow: none !important; }
        .no-print { display: none !important; }
      }`}</style>

      <div className="flex items-center justify-between no-print">
        <Link href="/payments" className="p-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 rounded-xl text-slate-400 hover:text-white transition-all">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <button onClick={() => window.print()} className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-2.5 px-5 rounded-xl text-xs flex items-center gap-2 transition-all">
          <Printer className="w-4 h-4" /> <span>Print / Save PDF</span>
        </button>
      </div>

      <div id="receipt-print" className="bg-white text-slate-900 rounded-2xl overflow-hidden shadow-xl relative">
        {reversed && (
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            <span className="text-[90px] font-black opacity-10 rotate-[-20deg] text-red-600">REVERSED</span>
          </div>
        )}
        <div className="px-8 py-6 text-white" style={{ background: brand }}>
          <div className="flex justify-between items-start">
            <div>
              <h2 className="text-2xl font-black">{property?.name || "Property"}</h2>
              <p className="text-xs opacity-80 mt-1">{[property?.address_line1, property?.city].filter(Boolean).join(", ")}</p>
            </div>
            <div className="text-right">
              <div className="text-lg font-black uppercase tracking-wide">Receipt</div>
              <div className="text-sm font-mono">{payment.receipt_number}</div>
            </div>
          </div>
        </div>

        <div className="px-8 py-6 space-y-4">
          <div className="grid grid-cols-2 gap-4 text-sm">
            <Field label="Received From" value={payment.tenant?.full_name} />
            <Field label="Date" value={new Date(payment.paid_at).toLocaleDateString()} right />
            <Field label="Method" value={payment.payment_method?.toUpperCase()} />
            <Field label="Reference" value={payment.reference_number || "—"} right />
            {payment.invoice && <Field label="Against Invoice" value={payment.invoice.invoice_number} />}
            {payment.invoice && <Field label="Room" value={`${payment.invoice.room?.room_number}-${payment.invoice.bed?.bed_label}`} right />}
          </div>

          <div className="flex justify-between items-center border-t border-slate-200 pt-4">
            <span className="text-sm font-bold text-slate-500 uppercase">Amount Received</span>
            <span className="text-2xl font-black" style={{ color: brand }}>{fmt(payment.amount)}</span>
          </div>

          {reversed && (
            <div className="text-xs text-red-600 border border-red-200 bg-red-50 rounded-lg p-3">
              This receipt was reversed. Reason: {payment.reversal_reason || "—"}
            </div>
          )}
        </div>

        <div className="px-8 py-4 bg-slate-50 text-[11px] text-slate-500 flex justify-between">
          <span>{property?.phone || ""}</span>
          <span>Generated by PG Manager</span>
        </div>
      </div>
    </div>
  );
}

function Field({ label, value, right }: { label: string; value: any; right?: boolean }) {
  return (
    <div className={right ? "text-right" : ""}>
      <div className="text-[10px] uppercase font-bold text-slate-400">{label}</div>
      <div className="font-semibold text-slate-800">{value}</div>
    </div>
  );
}
